// flow-typed signature: 2795d69f3c0c90e156e4de2cdd832084
// flow-typed version: <<STUB>>/dropbox_v3.0.4/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dropbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dropbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dropbox/dist/Dropbox-sdk' {
  declare module.exports: any;
}

declare module 'dropbox/dist/Dropbox-sdk.min' {
  declare module.exports: any;
}

declare module 'dropbox/dist/DropboxTeam-sdk' {
  declare module.exports: any;
}

declare module 'dropbox/dist/DropboxTeam-sdk.min' {
  declare module.exports: any;
}

declare module 'dropbox/es/constants' {
  declare module.exports: any;
}

declare module 'dropbox/es/download-request' {
  declare module.exports: any;
}

declare module 'dropbox/es/dropbox-base' {
  declare module.exports: any;
}

declare module 'dropbox/es/dropbox' {
  declare module.exports: any;
}

declare module 'dropbox/es/index.es6' {
  declare module.exports: any;
}

declare module 'dropbox/es/index' {
  declare module.exports: any;
}

declare module 'dropbox/es/object-assign-polyfill' {
  declare module.exports: any;
}

declare module 'dropbox/es/routes-team' {
  declare module.exports: any;
}

declare module 'dropbox/es/routes' {
  declare module.exports: any;
}

declare module 'dropbox/es/rpc-request' {
  declare module.exports: any;
}

declare module 'dropbox/es/team/dropbox-team' {
  declare module.exports: any;
}

declare module 'dropbox/es/team/index' {
  declare module.exports: any;
}

declare module 'dropbox/es/types' {
  declare module.exports: any;
}

declare module 'dropbox/es/upload-request' {
  declare module.exports: any;
}

declare module 'dropbox/es/utils' {
  declare module.exports: any;
}

declare module 'dropbox/generator/typescript/typescript-copy' {
  declare module.exports: any;
}

declare module 'dropbox/lib/constants' {
  declare module.exports: any;
}

declare module 'dropbox/lib/download-request' {
  declare module.exports: any;
}

declare module 'dropbox/lib/dropbox-base' {
  declare module.exports: any;
}

declare module 'dropbox/lib/dropbox' {
  declare module.exports: any;
}

declare module 'dropbox/lib/index.es6' {
  declare module.exports: any;
}

declare module 'dropbox/lib/index' {
  declare module.exports: any;
}

declare module 'dropbox/lib/object-assign-polyfill' {
  declare module.exports: any;
}

declare module 'dropbox/lib/routes-team' {
  declare module.exports: any;
}

declare module 'dropbox/lib/routes' {
  declare module.exports: any;
}

declare module 'dropbox/lib/rpc-request' {
  declare module.exports: any;
}

declare module 'dropbox/lib/team/dropbox-team' {
  declare module.exports: any;
}

declare module 'dropbox/lib/team/index' {
  declare module.exports: any;
}

declare module 'dropbox/lib/types' {
  declare module.exports: any;
}

declare module 'dropbox/lib/upload-request' {
  declare module.exports: any;
}

declare module 'dropbox/lib/utils' {
  declare module.exports: any;
}

declare module 'dropbox/rollup.config' {
  declare module.exports: any;
}

declare module 'dropbox/src/constants' {
  declare module.exports: any;
}

declare module 'dropbox/src/download-request' {
  declare module.exports: any;
}

declare module 'dropbox/src/dropbox-base' {
  declare module.exports: any;
}

declare module 'dropbox/src/dropbox' {
  declare module.exports: any;
}

declare module 'dropbox/src/index.es6' {
  declare module.exports: any;
}

declare module 'dropbox/src/index' {
  declare module.exports: any;
}

declare module 'dropbox/src/routes-team' {
  declare module.exports: any;
}

declare module 'dropbox/src/routes' {
  declare module.exports: any;
}

declare module 'dropbox/src/rpc-request' {
  declare module.exports: any;
}

declare module 'dropbox/src/team/dropbox-team' {
  declare module.exports: any;
}

declare module 'dropbox/src/team/index' {
  declare module.exports: any;
}

declare module 'dropbox/src/types' {
  declare module.exports: any;
}

declare module 'dropbox/src/upload-request' {
  declare module.exports: any;
}

declare module 'dropbox/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dropbox/dist/Dropbox-sdk.js' {
  declare module.exports: $Exports<'dropbox/dist/Dropbox-sdk'>;
}
declare module 'dropbox/dist/Dropbox-sdk.min.js' {
  declare module.exports: $Exports<'dropbox/dist/Dropbox-sdk.min'>;
}
declare module 'dropbox/dist/DropboxTeam-sdk.js' {
  declare module.exports: $Exports<'dropbox/dist/DropboxTeam-sdk'>;
}
declare module 'dropbox/dist/DropboxTeam-sdk.min.js' {
  declare module.exports: $Exports<'dropbox/dist/DropboxTeam-sdk.min'>;
}
declare module 'dropbox/es/constants.js' {
  declare module.exports: $Exports<'dropbox/es/constants'>;
}
declare module 'dropbox/es/download-request.js' {
  declare module.exports: $Exports<'dropbox/es/download-request'>;
}
declare module 'dropbox/es/dropbox-base.js' {
  declare module.exports: $Exports<'dropbox/es/dropbox-base'>;
}
declare module 'dropbox/es/dropbox.js' {
  declare module.exports: $Exports<'dropbox/es/dropbox'>;
}
declare module 'dropbox/es/index.es6.js' {
  declare module.exports: $Exports<'dropbox/es/index.es6'>;
}
declare module 'dropbox/es/index.js' {
  declare module.exports: $Exports<'dropbox/es/index'>;
}
declare module 'dropbox/es/object-assign-polyfill.js' {
  declare module.exports: $Exports<'dropbox/es/object-assign-polyfill'>;
}
declare module 'dropbox/es/routes-team.js' {
  declare module.exports: $Exports<'dropbox/es/routes-team'>;
}
declare module 'dropbox/es/routes.js' {
  declare module.exports: $Exports<'dropbox/es/routes'>;
}
declare module 'dropbox/es/rpc-request.js' {
  declare module.exports: $Exports<'dropbox/es/rpc-request'>;
}
declare module 'dropbox/es/team/dropbox-team.js' {
  declare module.exports: $Exports<'dropbox/es/team/dropbox-team'>;
}
declare module 'dropbox/es/team/index.js' {
  declare module.exports: $Exports<'dropbox/es/team/index'>;
}
declare module 'dropbox/es/types.js' {
  declare module.exports: $Exports<'dropbox/es/types'>;
}
declare module 'dropbox/es/upload-request.js' {
  declare module.exports: $Exports<'dropbox/es/upload-request'>;
}
declare module 'dropbox/es/utils.js' {
  declare module.exports: $Exports<'dropbox/es/utils'>;
}
declare module 'dropbox/generator/typescript/typescript-copy.js' {
  declare module.exports: $Exports<'dropbox/generator/typescript/typescript-copy'>;
}
declare module 'dropbox/lib/constants.js' {
  declare module.exports: $Exports<'dropbox/lib/constants'>;
}
declare module 'dropbox/lib/download-request.js' {
  declare module.exports: $Exports<'dropbox/lib/download-request'>;
}
declare module 'dropbox/lib/dropbox-base.js' {
  declare module.exports: $Exports<'dropbox/lib/dropbox-base'>;
}
declare module 'dropbox/lib/dropbox.js' {
  declare module.exports: $Exports<'dropbox/lib/dropbox'>;
}
declare module 'dropbox/lib/index.es6.js' {
  declare module.exports: $Exports<'dropbox/lib/index.es6'>;
}
declare module 'dropbox/lib/index.js' {
  declare module.exports: $Exports<'dropbox/lib/index'>;
}
declare module 'dropbox/lib/object-assign-polyfill.js' {
  declare module.exports: $Exports<'dropbox/lib/object-assign-polyfill'>;
}
declare module 'dropbox/lib/routes-team.js' {
  declare module.exports: $Exports<'dropbox/lib/routes-team'>;
}
declare module 'dropbox/lib/routes.js' {
  declare module.exports: $Exports<'dropbox/lib/routes'>;
}
declare module 'dropbox/lib/rpc-request.js' {
  declare module.exports: $Exports<'dropbox/lib/rpc-request'>;
}
declare module 'dropbox/lib/team/dropbox-team.js' {
  declare module.exports: $Exports<'dropbox/lib/team/dropbox-team'>;
}
declare module 'dropbox/lib/team/index.js' {
  declare module.exports: $Exports<'dropbox/lib/team/index'>;
}
declare module 'dropbox/lib/types.js' {
  declare module.exports: $Exports<'dropbox/lib/types'>;
}
declare module 'dropbox/lib/upload-request.js' {
  declare module.exports: $Exports<'dropbox/lib/upload-request'>;
}
declare module 'dropbox/lib/utils.js' {
  declare module.exports: $Exports<'dropbox/lib/utils'>;
}
declare module 'dropbox/rollup.config.js' {
  declare module.exports: $Exports<'dropbox/rollup.config'>;
}
declare module 'dropbox/src/constants.js' {
  declare module.exports: $Exports<'dropbox/src/constants'>;
}
declare module 'dropbox/src/download-request.js' {
  declare module.exports: $Exports<'dropbox/src/download-request'>;
}
declare module 'dropbox/src/dropbox-base.js' {
  declare module.exports: $Exports<'dropbox/src/dropbox-base'>;
}
declare module 'dropbox/src/dropbox.js' {
  declare module.exports: $Exports<'dropbox/src/dropbox'>;
}
declare module 'dropbox/src/index.es6.js' {
  declare module.exports: $Exports<'dropbox/src/index.es6'>;
}
declare module 'dropbox/src/index.js' {
  declare module.exports: $Exports<'dropbox/src/index'>;
}
declare module 'dropbox/src/routes-team.js' {
  declare module.exports: $Exports<'dropbox/src/routes-team'>;
}
declare module 'dropbox/src/routes.js' {
  declare module.exports: $Exports<'dropbox/src/routes'>;
}
declare module 'dropbox/src/rpc-request.js' {
  declare module.exports: $Exports<'dropbox/src/rpc-request'>;
}
declare module 'dropbox/src/team/dropbox-team.js' {
  declare module.exports: $Exports<'dropbox/src/team/dropbox-team'>;
}
declare module 'dropbox/src/team/index.js' {
  declare module.exports: $Exports<'dropbox/src/team/index'>;
}
declare module 'dropbox/src/types.js' {
  declare module.exports: $Exports<'dropbox/src/types'>;
}
declare module 'dropbox/src/upload-request.js' {
  declare module.exports: $Exports<'dropbox/src/upload-request'>;
}
declare module 'dropbox/src/utils.js' {
  declare module.exports: $Exports<'dropbox/src/utils'>;
}
