// flow-typed signature: 037f9f8c8e3b6f20e8ea0fd9fde887ee
// flow-typed version: <<STUB>>/rekit-studio_v2.2.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rekit-studio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rekit-studio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rekit-studio/dist/static/libs/d3.min' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/main' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/base/worker/workerMain' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/bat' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/coffee' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/cpp' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/csharp' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/css' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/dockerfile' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/fsharp' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/go' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/handlebars' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/html' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/ini' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/java' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/less' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/lua' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/markdown' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/msdax' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/objective-c' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/php' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/postiats' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/powershell' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/pug' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/python' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/r' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/razor' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/ruby' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/sb' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/scss' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/solidity' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/sql' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/swift' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/vb' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/xml' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/basic-languages/src/yaml' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.de' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.es' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.fr' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.hu' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.it' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.ja' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.ko' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.pt-br' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.ru' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.tr' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.zh-cn' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.zh-tw' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/language/css/cssMode' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/language/css/cssWorker' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/language/html/htmlMode' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/language/html/htmlWorker' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/language/json/jsonMode' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/language/json/jsonWorker' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/language/typescript/lib/typescriptServices' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/language/typescript/src/mode' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/language/typescript/src/worker' {
  declare module.exports: any;
}

declare module 'rekit-studio/dist/static/vs/loader' {
  declare module.exports: any;
}

declare module 'rekit-studio/middleware/api/execCmd' {
  declare module.exports: any;
}

declare module 'rekit-studio/middleware/api/fetchProjectData' {
  declare module.exports: any;
}

declare module 'rekit-studio/middleware/api/getFileContent' {
  declare module.exports: any;
}

declare module 'rekit-studio/middleware/api/runBuild' {
  declare module.exports: any;
}

declare module 'rekit-studio/middleware/api/runTest' {
  declare module.exports: any;
}

declare module 'rekit-studio/middleware/api/saveFile' {
  declare module.exports: any;
}

declare module 'rekit-studio/middleware/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rekit-studio/dist/static/libs/d3.min.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/libs/d3.min'>;
}
declare module 'rekit-studio/dist/static/main.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/main'>;
}
declare module 'rekit-studio/dist/static/vs/base/worker/workerMain.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/base/worker/workerMain'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/bat.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/bat'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/coffee.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/coffee'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/cpp.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/cpp'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/csharp.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/csharp'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/css.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/css'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/dockerfile.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/dockerfile'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/fsharp.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/fsharp'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/go.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/go'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/handlebars.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/handlebars'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/html.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/html'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/ini.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/ini'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/java.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/java'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/less.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/less'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/lua.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/lua'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/markdown.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/markdown'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/msdax.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/msdax'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/objective-c.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/objective-c'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/php.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/php'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/postiats.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/postiats'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/powershell.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/powershell'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/pug.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/pug'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/python.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/python'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/r.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/r'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/razor.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/razor'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/ruby.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/ruby'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/sb.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/sb'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/scss.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/scss'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/solidity.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/solidity'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/sql.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/sql'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/swift.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/swift'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/vb.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/vb'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/xml.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/xml'>;
}
declare module 'rekit-studio/dist/static/vs/basic-languages/src/yaml.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/basic-languages/src/yaml'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.de.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.de'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.es.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.es'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.fr.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.fr'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.hu.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.hu'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.it.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.it'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.ja.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.ja'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.ko.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.ko'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.pt-br.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.pt-br'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.ru.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.ru'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.tr.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.tr'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.zh-cn.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.zh-cn'>;
}
declare module 'rekit-studio/dist/static/vs/editor/editor.main.nls.zh-tw.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/editor/editor.main.nls.zh-tw'>;
}
declare module 'rekit-studio/dist/static/vs/language/css/cssMode.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/language/css/cssMode'>;
}
declare module 'rekit-studio/dist/static/vs/language/css/cssWorker.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/language/css/cssWorker'>;
}
declare module 'rekit-studio/dist/static/vs/language/html/htmlMode.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/language/html/htmlMode'>;
}
declare module 'rekit-studio/dist/static/vs/language/html/htmlWorker.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/language/html/htmlWorker'>;
}
declare module 'rekit-studio/dist/static/vs/language/json/jsonMode.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/language/json/jsonMode'>;
}
declare module 'rekit-studio/dist/static/vs/language/json/jsonWorker.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/language/json/jsonWorker'>;
}
declare module 'rekit-studio/dist/static/vs/language/typescript/lib/typescriptServices.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/language/typescript/lib/typescriptServices'>;
}
declare module 'rekit-studio/dist/static/vs/language/typescript/src/mode.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/language/typescript/src/mode'>;
}
declare module 'rekit-studio/dist/static/vs/language/typescript/src/worker.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/language/typescript/src/worker'>;
}
declare module 'rekit-studio/dist/static/vs/loader.js' {
  declare module.exports: $Exports<'rekit-studio/dist/static/vs/loader'>;
}
declare module 'rekit-studio/middleware/api/execCmd.js' {
  declare module.exports: $Exports<'rekit-studio/middleware/api/execCmd'>;
}
declare module 'rekit-studio/middleware/api/fetchProjectData.js' {
  declare module.exports: $Exports<'rekit-studio/middleware/api/fetchProjectData'>;
}
declare module 'rekit-studio/middleware/api/getFileContent.js' {
  declare module.exports: $Exports<'rekit-studio/middleware/api/getFileContent'>;
}
declare module 'rekit-studio/middleware/api/runBuild.js' {
  declare module.exports: $Exports<'rekit-studio/middleware/api/runBuild'>;
}
declare module 'rekit-studio/middleware/api/runTest.js' {
  declare module.exports: $Exports<'rekit-studio/middleware/api/runTest'>;
}
declare module 'rekit-studio/middleware/api/saveFile.js' {
  declare module.exports: $Exports<'rekit-studio/middleware/api/saveFile'>;
}
declare module 'rekit-studio/middleware/index.js' {
  declare module.exports: $Exports<'rekit-studio/middleware/index'>;
}
