// flow-typed signature: 1750ea0d1f6b73d73748d28cbc2c413c
// flow-typed version: <<STUB>>/rekit-core_v2.2.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rekit-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rekit-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rekit-core/core/action' {
  declare module.exports: any;
}

declare module 'rekit-core/core/app' {
  declare module.exports: any;
}

declare module 'rekit-core/core/assert' {
  declare module.exports: any;
}

declare module 'rekit-core/core/component' {
  declare module.exports: any;
}

declare module 'rekit-core/core/constant' {
  declare module.exports: any;
}

declare module 'rekit-core/core/entry' {
  declare module.exports: any;
}

declare module 'rekit-core/core/feature' {
  declare module.exports: any;
}

declare module 'rekit-core/core/index' {
  declare module.exports: any;
}

declare module 'rekit-core/core/plugin' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/array' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/cls' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/common' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/func' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/identifier' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/importExport' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/index' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/lines' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/object' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/string' {
  declare module.exports: any;
}

declare module 'rekit-core/core/refactor/style' {
  declare module.exports: any;
}

declare module 'rekit-core/core/route' {
  declare module.exports: any;
}

declare module 'rekit-core/core/style' {
  declare module.exports: any;
}

declare module 'rekit-core/core/template' {
  declare module.exports: any;
}

declare module 'rekit-core/core/test' {
  declare module.exports: any;
}

declare module 'rekit-core/core/utils' {
  declare module.exports: any;
}

declare module 'rekit-core/core/vio' {
  declare module.exports: any;
}

declare module 'rekit-core/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'rekit-core/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'rekit-core/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/Component' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/Component.test' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/ConnectedComponent' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/ConnectedComponent.test' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/index' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/reducer.test' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/redux/action' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/redux/action.test' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/redux/actions' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/redux/async_action' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/redux/async_action.test' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/redux/constants' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/redux/initialState' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/redux/reducer' {
  declare module.exports: any;
}

declare module 'rekit-core/templates/route' {
  declare module.exports: any;
}

declare module 'rekit-core/test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/action.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/async-action.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/component.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/constant.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/entry.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/feature.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/helpers' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/npm' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/refactor.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/refactor/array.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/refactor/common.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/refactor/identifier.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/rekit' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/route.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/template.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/test-prj/src/common/configStore' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/test-prj/src/common/rootReducer' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/test-prj/src/common/routeConfig' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/utils.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tests/vio.test' {
  declare module.exports: any;
}

declare module 'rekit-core/tools/run_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rekit-core/core/action.js' {
  declare module.exports: $Exports<'rekit-core/core/action'>;
}
declare module 'rekit-core/core/app.js' {
  declare module.exports: $Exports<'rekit-core/core/app'>;
}
declare module 'rekit-core/core/assert.js' {
  declare module.exports: $Exports<'rekit-core/core/assert'>;
}
declare module 'rekit-core/core/component.js' {
  declare module.exports: $Exports<'rekit-core/core/component'>;
}
declare module 'rekit-core/core/constant.js' {
  declare module.exports: $Exports<'rekit-core/core/constant'>;
}
declare module 'rekit-core/core/entry.js' {
  declare module.exports: $Exports<'rekit-core/core/entry'>;
}
declare module 'rekit-core/core/feature.js' {
  declare module.exports: $Exports<'rekit-core/core/feature'>;
}
declare module 'rekit-core/core/index.js' {
  declare module.exports: $Exports<'rekit-core/core/index'>;
}
declare module 'rekit-core/core/plugin.js' {
  declare module.exports: $Exports<'rekit-core/core/plugin'>;
}
declare module 'rekit-core/core/refactor/array.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/array'>;
}
declare module 'rekit-core/core/refactor/cls.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/cls'>;
}
declare module 'rekit-core/core/refactor/common.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/common'>;
}
declare module 'rekit-core/core/refactor/func.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/func'>;
}
declare module 'rekit-core/core/refactor/identifier.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/identifier'>;
}
declare module 'rekit-core/core/refactor/importExport.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/importExport'>;
}
declare module 'rekit-core/core/refactor/index.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/index'>;
}
declare module 'rekit-core/core/refactor/lines.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/lines'>;
}
declare module 'rekit-core/core/refactor/object.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/object'>;
}
declare module 'rekit-core/core/refactor/string.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/string'>;
}
declare module 'rekit-core/core/refactor/style.js' {
  declare module.exports: $Exports<'rekit-core/core/refactor/style'>;
}
declare module 'rekit-core/core/route.js' {
  declare module.exports: $Exports<'rekit-core/core/route'>;
}
declare module 'rekit-core/core/style.js' {
  declare module.exports: $Exports<'rekit-core/core/style'>;
}
declare module 'rekit-core/core/template.js' {
  declare module.exports: $Exports<'rekit-core/core/template'>;
}
declare module 'rekit-core/core/test.js' {
  declare module.exports: $Exports<'rekit-core/core/test'>;
}
declare module 'rekit-core/core/utils.js' {
  declare module.exports: $Exports<'rekit-core/core/utils'>;
}
declare module 'rekit-core/core/vio.js' {
  declare module.exports: $Exports<'rekit-core/core/vio'>;
}
declare module 'rekit-core/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'rekit-core/docs/scripts/linenumber'>;
}
declare module 'rekit-core/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'rekit-core/docs/scripts/prettify/lang-css'>;
}
declare module 'rekit-core/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'rekit-core/docs/scripts/prettify/prettify'>;
}
declare module 'rekit-core/index' {
  declare module.exports: $Exports<'rekit-core'>;
}
declare module 'rekit-core/index.js' {
  declare module.exports: $Exports<'rekit-core'>;
}
declare module 'rekit-core/templates/Component.js' {
  declare module.exports: $Exports<'rekit-core/templates/Component'>;
}
declare module 'rekit-core/templates/Component.test.js' {
  declare module.exports: $Exports<'rekit-core/templates/Component.test'>;
}
declare module 'rekit-core/templates/ConnectedComponent.js' {
  declare module.exports: $Exports<'rekit-core/templates/ConnectedComponent'>;
}
declare module 'rekit-core/templates/ConnectedComponent.test.js' {
  declare module.exports: $Exports<'rekit-core/templates/ConnectedComponent.test'>;
}
declare module 'rekit-core/templates/index.js' {
  declare module.exports: $Exports<'rekit-core/templates/index'>;
}
declare module 'rekit-core/templates/reducer.test.js' {
  declare module.exports: $Exports<'rekit-core/templates/reducer.test'>;
}
declare module 'rekit-core/templates/redux/action.js' {
  declare module.exports: $Exports<'rekit-core/templates/redux/action'>;
}
declare module 'rekit-core/templates/redux/action.test.js' {
  declare module.exports: $Exports<'rekit-core/templates/redux/action.test'>;
}
declare module 'rekit-core/templates/redux/actions.js' {
  declare module.exports: $Exports<'rekit-core/templates/redux/actions'>;
}
declare module 'rekit-core/templates/redux/async_action.js' {
  declare module.exports: $Exports<'rekit-core/templates/redux/async_action'>;
}
declare module 'rekit-core/templates/redux/async_action.test.js' {
  declare module.exports: $Exports<'rekit-core/templates/redux/async_action.test'>;
}
declare module 'rekit-core/templates/redux/constants.js' {
  declare module.exports: $Exports<'rekit-core/templates/redux/constants'>;
}
declare module 'rekit-core/templates/redux/initialState.js' {
  declare module.exports: $Exports<'rekit-core/templates/redux/initialState'>;
}
declare module 'rekit-core/templates/redux/reducer.js' {
  declare module.exports: $Exports<'rekit-core/templates/redux/reducer'>;
}
declare module 'rekit-core/templates/route.js' {
  declare module.exports: $Exports<'rekit-core/templates/route'>;
}
declare module 'rekit-core/test.js' {
  declare module.exports: $Exports<'rekit-core/test'>;
}
declare module 'rekit-core/tests/action.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/action.test'>;
}
declare module 'rekit-core/tests/async-action.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/async-action.test'>;
}
declare module 'rekit-core/tests/component.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/component.test'>;
}
declare module 'rekit-core/tests/constant.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/constant.test'>;
}
declare module 'rekit-core/tests/entry.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/entry.test'>;
}
declare module 'rekit-core/tests/feature.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/feature.test'>;
}
declare module 'rekit-core/tests/helpers.js' {
  declare module.exports: $Exports<'rekit-core/tests/helpers'>;
}
declare module 'rekit-core/tests/npm.js' {
  declare module.exports: $Exports<'rekit-core/tests/npm'>;
}
declare module 'rekit-core/tests/refactor.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/refactor.test'>;
}
declare module 'rekit-core/tests/refactor/array.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/refactor/array.test'>;
}
declare module 'rekit-core/tests/refactor/common.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/refactor/common.test'>;
}
declare module 'rekit-core/tests/refactor/identifier.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/refactor/identifier.test'>;
}
declare module 'rekit-core/tests/rekit.js' {
  declare module.exports: $Exports<'rekit-core/tests/rekit'>;
}
declare module 'rekit-core/tests/route.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/route.test'>;
}
declare module 'rekit-core/tests/template.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/template.test'>;
}
declare module 'rekit-core/tests/test-prj/src/common/configStore.js' {
  declare module.exports: $Exports<'rekit-core/tests/test-prj/src/common/configStore'>;
}
declare module 'rekit-core/tests/test-prj/src/common/rootReducer.js' {
  declare module.exports: $Exports<'rekit-core/tests/test-prj/src/common/rootReducer'>;
}
declare module 'rekit-core/tests/test-prj/src/common/routeConfig.js' {
  declare module.exports: $Exports<'rekit-core/tests/test-prj/src/common/routeConfig'>;
}
declare module 'rekit-core/tests/utils.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/utils.test'>;
}
declare module 'rekit-core/tests/vio.test.js' {
  declare module.exports: $Exports<'rekit-core/tests/vio.test'>;
}
declare module 'rekit-core/tools/run_test.js' {
  declare module.exports: $Exports<'rekit-core/tools/run_test'>;
}
